# Generated by Django 4.0.6 on 2022-07-16 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(default='', max_length=350)),
                ('phone', models.CharField(default='', max_length=12)),
                ('website', models.URLField(default='')),
                ('description', models.TextField(default='', max_length=500)),
                ('image', models.ImageField(default='https://m.media-amazon.com/images/I/4193V9-69jS._AC_SY780_.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('interested_in', models.CharField(default='', max_length=350)),
                ('availability', models.CharField(default='', max_length=350)),
                ('introduce_yourself', models.TextField(default='', max_length=500)),
                ('image', models.ImageField(default='https://cdn3.vectorstock.com/i/1000x1000/30/97/flat-business-man-user-profile-avatar-icon-vector-4333097.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=60)),
                ('description', models.TextField(default='', max_length=500)),
                ('skills', models.TextField(default='', max_length=500)),
                ('location', models.CharField(default='', max_length=350)),
                ('time', models.CharField(default='', max_length=350)),
                ('image', models.ImageField(default='https://www.covenantgroup.com/img/84', upload_to='images/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteerUofG.charity')),
            ],
        ),
    ]
