# Generated by Django 4.0.6 on 2022-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerUofG', '0002_charity_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
