# Generated by Django 4.0.6 on 2022-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerUofG', '0003_opportunity_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='charity',
            name='image',
            field=models.ImageField(blank=True, default='https://m.media-amazon.com/images/I/4193V9-69jS._AC_SY780_.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, default='https://www.covenantgroup.com/img/84', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, default='https://cdn3.vectorstock.com/i/1000x1000/30/97/flat-business-man-user-profile-avatar-icon-vector-4333097.jpg', null=True, upload_to=''),
        ),
    ]
