# Generated by Django 4.0.6 on 2022-08-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerUofG', '0004_remove_charity_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
