# Generated by Django 4.0.6 on 2022-08-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteerUofG', '0006_alter_charity_image_alter_opportunity_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='image',
            field=models.ImageField(blank=True, default='https://m.media-amazon.com/images/I/4193V9-69jS._AC_SY780_.jpg', null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, default='https://www.covenantgroup.com/img/84', null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, default='https://cdn3.vectorstock.com/i/1000x1000/30/97/flat-business-man-user-profile-avatar-icon-vector-4333097.jpg', null=True, upload_to='profile_images'),
        ),
    ]
